added support for SFRPG
League-of-Foundry-Developers/fvtt-module-lmrtfy pull request #107
Opened 2021-06-21 14:02 UTC by Yukonite

Hi! I believe I've added support for SFRPG, though I'll need to review in Foundry to confirm. Thanks for building this module!

2021-06-22 20:49 UTC, Varriount requested changes

2021-06-22 20:49 UTC, Varriount commented on module.json
> +    "languages": [{
The change on these two lines needs to be reverted (slight formatting inconsistency).
Same for line 66 and 88.

2021-06-22 20:49 UTC, Varriount commented on src/lmrtfy.js
> +        Handlebars.registerHelper('lmrtfy-controlledToken', function(actor) {
```suggestion
        Handlebars.registerHelper('lmrtfy-controlledToken', function (actor) {
```

2021-06-22 20:49 UTC, Varriount commented on src/lmrtfy.js
> +            // Resize to fit the new theme
```suggestion
        // Resize to fit the new theme
```

2021-06-22 20:49 UTC, Varriount commented on src/lmrtfy.js
> +Hooks.on('renderChatMessage', LMRTFY.hideBlind);
Please add a newline to the end of the file.

2021-06-22 20:50 UTC, Varriount commented
The PR looks good, you mainly need to revert some formatting changes that occurred. Please comment when you have had a chance to test your changes in Foundry.

2021-06-23 14:02 UTC, vtt-lair commented
@Yukonite can you possible supply me with the "mod" name for the modifier of your actor's ability rolls? In other words if you roll a strength ability check, what variable is used? For instance in DnD5E it's "@abilities.dex.mod". 

This is for my PR #106 that will bring a bit more functionality to the custom formula field. Just so that I can add them, as your PR will probably be going first (and would make more sense for me to wait for yours to be merged in first)

2021-06-23 14:17 UTC, Yukonite commented
@vtt-lair The formatting is the same as noted above - "@abilities.dex.mod"

2021-06-23 14:44 UTC, Yukonite commented on src/lmrtfy.js
> +            // Resize to fit the new theme
Changed.

2021-06-23 14:51 UTC, Yukonite commented
@Varriount Tested in Foundry. The only skill check that won't work with the existing code is Initiative because the attribute value is 'init' not 'initiative' in the SFRPG system. I can try a workaround with something like:

`LMRTFY.specialRolls = { 'init': true };` or `LMRTFY.specialRolls = { 'SFRPGinit': true };`

and then make adjustments to the HTML, roller, and requestor. Thoughts?

2021-06-23 19:23 UTC, Varriount commented
@Yukonite I'm unfamiliar with SFRPG (and also LMRTFY - I just review general PRs for https://github.com/League-of-Foundry-Developers ). Regular initiative rolls add the user's selected token to the combat tracker, if there is a combat available. I would recommend installing another system and testing in that one (Pathfinder or D&D 5e both have an "initiative" concept).

2021-06-25 13:21 UTC, vtt-lair commented
@Yukonite if you pull the latest to your branch you'll have the added dice feature below the custom formula field. To make sure it works for SFRPG too, please add the following 3 lines to your case:

`
LMRTFY.abilityAbbreviations = CONFIG.SFRPG.abilityAbbreviations;
LMRTFY.modIdentifier = 'mod';
LMRTFY.abilityModifiers = LMRTFY.parseAbilityModifiers();
`

Then regarding your initiative question. I quickly tried it on a DnD5e system to see what happens... and from what I can see currently the initiative and death saving throw doesn't seem to be working. I'll try and spend some time over the weekend to figure out what is going and and why it's not working... I don't really use LMRTFY's initiative or death saves feature in my games.

2022-05-26 22:29 UTC, closed without merging

2022-05-26 22:30 UTC, Yukonite commented
Old pull request. I may update when I get LMRTFY working with SFRPG again.